# Generated by Django 4.0.3 on 2022-08-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freeanswer',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='freecontent',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
