# Generated by Django 4.0.3 on 2022-08-18 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sports', '0003_freeanswer_author_freecontent_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='freeanswer',
            name='recommend',
            field=models.ManyToManyField(related_name='recommend_answer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='freecontent',
            name='recommend',
            field=models.ManyToManyField(related_name='recommend_content', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='freeanswer',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_answer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='freecontent',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_content', to=settings.AUTH_USER_MODEL),
        ),
    ]
