# Generated by Django 4.0.3 on 2022-08-21 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0004_freeanswer_recommend_freecontent_recommend_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freecontent',
            name='hits',
            field=models.PositiveIntegerField(default=1, verbose_name='hits'),
        ),
    ]
