# Generated by Django 4.0.3 on 2022-08-25 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_customuser_auth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='auth',
        ),
        migrations.AddField(
            model_name='customuser',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tier',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
