# Generated by Django 4.0.3 on 2022-08-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_remove_customuser_auth_customuser_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='auth',
            field=models.CharField(max_length=10, null=True, verbose_name='인증번호'),
        ),
    ]
