# Generated by Django 4.0.3 on 2022-08-21 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchSports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('sports_name', models.CharField(max_length=50)),
                ('sports_date', models.DateField()),
                ('address', models.CharField(max_length=200)),
                ('people_limit', models.PositiveIntegerField(default=1, verbose_name='people_limit')),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField()),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('hits', models.PositiveIntegerField(default=1, verbose_name='hits')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_match', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
