# Generated by Django 4.0.3 on 2022-08-23 12:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchsports',
            name='people_limit',
        ),
        migrations.AddField(
            model_name='matchsports',
            name='people_limit',
            field=models.ManyToManyField(related_name='people_limit', to=settings.AUTH_USER_MODEL),
        ),
    ]
