# Generated by Django 4.0.3 on 2022-08-23 12:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_remove_matchsports_people_limit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchsports',
            name='people_limit',
        ),
        migrations.AddField(
            model_name='matchsports',
            name='apply_count',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='matchsports',
            name='max_apply',
            field=models.PositiveIntegerField(default=1, verbose_name='max_apply'),
        ),
    ]
