# Generated by Django 4.0.3 on 2022-08-23 14:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('match', '0003_remove_matchsports_people_limit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchsports',
            name='apply_count',
        ),
        migrations.AddField(
            model_name='matchsports',
            name='apply_count',
            field=models.ManyToManyField(related_name='apply_count', to=settings.AUTH_USER_MODEL),
        ),
    ]
